class LocatorsXpath:
    name = "//input[@name='name']"
    email = "//span/input[@name='email']"
    telephone = "//input[@name='telephone']"
    country = "//input[@name='country']"
    company = "//input[@name='company']"
    message = "//textarea[@name='message']"
    submit = "//a[text()='Submit']"
    clear = "//a[text()='clear']"
    name_error_message = "//div[@class='form-validation-field-0formError parentFormundefined formError']/div[text() = '* This field is required']"
    name_error_form = "//div[@class='form-validation-field-0formError parentFormundefined formError']"
    success_message = "//div[text()='Feedback has been sent to the administrator']"
    email_error_message = "//*[contains(text(), 'This field is required') or contains(text(), 'Invalid email address')]"
    phone_error_message = "//*[contains(text(), 'This field is required') or contains(text(), 'Invalid phone number')]"
    country_error_message = ""